package enigma;


public enum RotorType {
	I("EKMFLGDQVZNTOWYHXUSPAIBRCJ"),
	II("AJDKSIRUXBLHWTMCQGZNPYFVOE"),
	III("BDFHJLCPRTXVZNYEIWGAKMUSQO"),
	IV("ESOVPZJAYQUIRHXLNFTGKDCMWB"),
	V("VZBRGITYUPSDNHLXAWMJQOFECK"),
	VI("JPGVOUMFYQBENHZRDKASXLICTW"),
	VII("NZJHGRCXMYSWBOUFAIVLPEKQDT"),
	VIII("FKQHTLXOCBJSPDZRAMEWNIUYGV");
	private final String map;
	public String map() { return map; }
	RotorType(String map) { this.map = map; }
}